// Generated by CoffeeScript 1.3.1
(function() {
  var TopicModel;

  TopicModel = require('./topicModel').TopicModel;

  ({
    printTestResult: function(testName, errors) {
      if (errors.length > 0) {
        console.log("the following tests failed for " + testName + ":");
        return console.dir(errors);
      } else {
        return console.log("" + testName + " OK");
      }
    },
    testGetUrlFromTitle: function() {
      var errors, m;
      m = new TopicModel();
      errors = [];
      if (m._getUrlFromTitle("hello") !== "hello") {
        errors.push("basic test");
      }
      if (m._getUrlFromTitle("hello-World") !== "hello-world") {
        errors.push("lowercase test");
      }
      if (m._getUrlFromTitle("hello-World.aspx") !== "hello-world-aspx") {
        errors.push("dots test");
      }
      if (m._getUrlFromTitle("hello-c#-World.aspx") !== "hello-csharp-world-aspx") {
        errors.push("c# test");
      }
      if (m._getUrlFromTitle("this is #4") !== "this-is--4") {
        errors.push("pound (#) test");
      }
      return printTestResult("_getUrlFromTitle", errors);
    }
  });

  testGetUrlFromTitle();

}).call(this);
